### ISSUE TITLE
Interesting div stacking issue

### ISSUE THREAD

**Issue by ZebGirouard** [jessHwood/SuperSnakeGame#2]
When screen width is just a little too small (I have my browser zoomed in to 125%), the rules stacked on top of the game in an interesting diagonal pattern like this:
<img width="897" alt="screen shot 2017-03-31 at 4 33 02 pm" src="https://cloud.githubusercontent.com/assets/5480464/24571645/efc885fc-162f-11e7-91a9-bb691658e610.png">

Is this an easy fix?

**Comment by jessHwood** [comment]
Fixed issue by styling div above the snake game - works responsively as well.
